### ISSUE TITLE
Migration to node 10

### ISSUE THREAD

**Issue by eneam** [cagataygurturk/image-resizer-service#9]
AWS Lambda: Node.js 8.10 is EOL, please migration your functions to a newer runtime version

any suggestions for migration?

**Comment by nbonnefoy** [comment]
Strange behavior in node10.x, the KEY is not parsed properly.
The output logs seems to indicate that it takes "favicon.ico" instead of the real key parameter :
INFO: key: favicon.ico
ERROR 404 NoSuchKey { NoSuchKey: The specified key does not exist.

**Comment by thepofo** [comment]
Any feedback on upgrading to Node 10? AWS notified me already a couple of times about end of life...

**Comment by thepofo** [comment]
The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 3f8ac475-efba-4fc6-9aa4-5a150540a622)

**Comment by jainarpit014** [comment]
AWS doesn't allow deploying this lambda application anymore due to Node js 8.10 EOL. Any plans to upgrade?

**Comment by eneam** [comment]
the new node 10+ AWS runtime container does not have image magick you have to add "image-magick" layer for the lambda to work

**Comment by ricardoroth** [comment]
> the new node 10+ AWS runtime container does not have image magick you have to add "image-magick" layer for the lambda to work

Is this a solution to make the deployment? can you give more details?

**Comment by cagataygurturk** [comment]
Hey all, sorry for the late feedback, nowadays I am busy with GCP and away from AWS ecosystem.

I have updated the application to Node 10 but as @eneam pointed out, there is no Imagick binaries in the runtime anymore. Please check the Readme for instructions to workaround this using [this another application](https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:145266761615:applications/image-magick-lambda-layer).

I am gonna try to embed this Lambda layer into this application in a next version.

**Comment by Andresgonzale** [comment]
[Uploading Security Updates 2022-03-28-084712pm.xlsx…]()
